List structure for To-do List
dhirajsingha143/To-do_list pull request #1
Opened 2023-01-20 16:59 UTC by dhirajsingha143

### TO-DO LIST Milestone-1
- Setup web pack
- Installed HTML plugin for webpack
- Installed CSS plugin for webpack
- Installed webpack dev server for local hosting
- Created HTML, CSS and JS files
- Add basic markup structure and styling
- Add functionality and used ES6 syntax
- Installed Linters actions

2023-01-20 17:39 UTC, Tadesse-Alemayehu requested changes
### Hi @dhirajsingha143 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)

## Highlights
 - [ ] Good job overall following the template design ✅
 - [ ]  Correct GitHub Flow  ✅
 - [ ]  Good commit history  ✅
 - [ ]  Good PR title/description  ✅
 - [ ]  All linters passed  ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 17:39 UTC, Tadesse-Alemayehu commented on src/index.js
> +};
- [ ] I'm impressed with the step you have taken @dhirajsingha143, But as a main requirement for this project the project should have an initial array with some simple *to do tasks* (array of objects) with each object containing three keys - description \[`string`\], completed \[`bool`\], index: \[`number`\].

2023-01-20 17:39 UTC, Tadesse-Alemayehu commented on src/style.css
> +}
- [ ] Dear @dhirajsingha143, Your styling is great, But we need to stick to the given design. You don't have to do all the functionalities as in the provided vide but the layout should lookalike the one given.

### Your design 
![Screenshot 2023-01-20 203235](https://user-images.githubusercontent.com/69077061/213766015-7544cc9d-909e-411b-823d-28f5593b261b.png)

### Given design
![Screenshot 2023-01-20 203300](https://user-images.githubusercontent.com/69077061/213766089-2d1a0ff1-2bc5-4290-aaf0-05b41aa3698e.png)

2023-01-21 06:23 UTC, jerryowusu requested changes
Hi @dhirajsingha143  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![no-we-were-so-close-pauline-turner-brooks](https://user-images.githubusercontent.com/65233860/213846691-55367fcc-8790-471b-bce8-cc9cf63a6575.gif)

 ## Highlights
Nice commit messages :heavy_check_mark: 
Used github flow :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 06:23 UTC, jerryowusu commented on src/index.js
> +
As requested by the previous reviewer, you do not need to implement all the tasks at once, kindly focus on the current activity as shown below :point_down: As a main requirement at this stage of  the project you just have to have an initial array with some simple to do tasks (array of objects) with each object containing three keys - description [string], completed [bool], index: [number]. 


![Screenshot from 2023-01-21 06-18-53](https://user-images.githubusercontent.com/65233860/213846522-aad2d61d-9af4-4b70-abe4-c16200a3289c.png)

2023-01-21 06:23 UTC, jerryowusu commented on src/style.css
> +  /* stylelint-disable-next-line */
[OPTIONAL] The linters are suppose to guide you to achieve best standard practices, so it is not a good practice to disable parts of it. Kindly consider removing this line :pray:

2023-01-21 06:53 UTC, muneebulrehman approved these changes
Hi @dhirajsingha143 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Descriptive PR
- All requirements met for this milestone.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 06:56 UTC, merged